### PR TITLE
New container for an upcoming PR

### PR DESCRIPTION
**Pull request by ignaciot**
Bumping FastQC's version to both take advantage of the newer tool, and generate a new container to get ready for an upcoming major PR. Updated the environment and changelog files accordingly, and any additional changes incorporated after running `--bump-version` to `1.0.2dev`.

## PR checklist
 - [X] This comment contains a description of changes (with reason)
 - [X] Make sure your code lints (`nf-core lint .`).
 - [X] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by ignaciot** [comment]
FYI, those missing 3 files the build is complaining about (branch, ci, and linting yaml files part of the new template) are present in the new version, this PR is just to create the dev container to test everything in the new version.

**Comment by ignaciot** [comment]
Of course! I got those taken care of already, and it passes the linter validation. Thanks!

**Comment by ignaciot** [comment]
Ugh, it seems I need to add those files anyway otherwise it won't allow me to merge.

**Comment by ignaciot** [comment]
> Ugh, it seems I need to add those files anyway otherwise it won't allow me to merge.

I'll just submit a PR for the entire dev branch. There are so many changes introduced with this template update that just the new yaml environment and changelog won't cut it, to pass CI. And creating an intermediate PR with just the template conflicts seems like a lot of unnecessary work...

**Comment by Emiller88** [comment]
Closing since #24 merged into dev

**Pull request closed without merging**
