### PR TITLE
Fixing linting errors and stuff like that

### PR DESCRIPTION
**Pull request by apeltzer**
## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] If necessary, also make a PR on the [nf-core/nascent branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/nascent)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/nascent/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by apeltzer** [comment]
@ignaciot - I have some parts that I miss in here. I marked these with `TODO IGNACIO` to set e.g. proper default values in `nextflow.config` in here. I fixed your tests, merged in the template v1.6 and also got it hopefully fixed in terms of markdown linting errors. 

This now follows the latest nf-core guidelines for most parts - still maybe requiring some more docs and polishing here and there before doing the final release. If you could adjust these points, then I'd be happy for reviewing THIS week and doing an initial 1.0 release 👍

**Comment by apeltzer** [comment]
Also, I noticed there are a couple of things missing - its just running the first three steps of the pipeline and nothing else....

**Comment by ignaciot** [comment]
Thanks for looking at this so quickly, @apeltzer! I'm not sure what may be going on, since the pipeline was running end to end with no errors, I will take a look now and see if we can finish this week.

**Comment by apeltzer** [comment]
We can and we will 💪

**Comment by ignaciot** [comment]
OK, this is related to the new template merge. It looks like the reason this only ran the first three steps is that it's not being able to read the test fastq file properly in this version (I simply had a parameter `reads = "https://raw.githubusercontent.com/nf-core/test-datasets/nascent/testdata/SRR4012402.chr21.fastq"` instead of the current `readPaths = [ ['SRR4012402', ['https://raw.githubusercontent.com/nf-core/test-datasets/nascent/testdata/SRR4012402.chr21.fastq']], ]`. Debugging...

**Comment by apeltzer** [comment]
But that readPaths map instead is poured into the read channels instead of the reads as it wasn't parsed properly during the tests (checked it myself).

**Comment by ignaciot** [comment]
Yeah, this Should Work™ the way it's written, must be something subtle. Just ran the test pipeline again from my original branch to make sure I'm not crazy (yet 😂) and ran fine, I'll figure it out.

**Comment by apeltzer** [comment]
I'll be online a while to help in case - can also chat on Slack and create a channel there

**Comment by apeltzer** [comment]
Found the problem: Its the `chr21` in your testdatasets that did the error + the combination of input channels. I was able to update the tests accordingly without changing too much and it runs through now I think 👍 


Linting is now fine with V1.6 template changes introduced: 

```
INFO: ===========
 LINTING RESULTS
=================
  80 tests passed   0 tests had warnings   0 tests failed
```

**Comment by ignaciot** [comment]
:+1: :+1:

**Pull request merged**
