### PR TITLE
Release lint plus bumping the version to 1.0

### PR DESCRIPTION
**Pull request by ignaciot**
First release ready for review.

Many thanks to contributing to nf-core/nascent!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/nascent branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/nascent)
 - [X] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [X] Make sure your code lints (`nf-core lint .`).
 - [X] Documentation in `docs` is updated
 - [X] `CHANGELOG.md` is updated
 - [X] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/nascent/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by apeltzer** [comment]
I’ll review asap

**Comment by ignaciot** [comment]
> I’ll review asap

Thanks, @apeltzer! Looks like the build failed because it's trying to pull the docker container from an inexistent tag (1.0, which was added by the version bump for the release, but only features `dev` and `latest`). Would you guys be able to create this tag? I can also update the `.travis.yaml` file to use `latest` instead, just let me know and I'll be happy to make the change... whatever is the easiest.

**Comment by apeltzer** [comment]
The TAG will just be created once you do a release. For the testing part, the idea is to test always using the `dev` branch and retagging as is afterward. I retriggered your tests, but the image on `dev` can be pulled which is weird that your tests actually failed.

**Comment by apeltzer** [comment]
I'll make a couple of PRs to get this in sync for now 👍

**Pull request closed without merging**
